export const draft = [
  {
    id: "a10",
    name: "Bels Pils",
    prices: [3.5, 6.3, 5.0],
    strength: 5.0,
  },
  {
    id: "a11",
    name: "Vedett Extra White",
    prices: [4.3, 7.7, 5.8],
    strength: 4.7,
  },
  {
    id: "a12",
    name: "Faro Lindemans",
    prices: [4.0, 7.2, 6.5],
    strength: 4.5,
  },
  {
    id: "a13",
    name: "Maredsous blonde",
    prices: [4.0, 7.2, 5.2],
    strength: 6.5,
  },
  {
    id: "a14",
    name: "Machette",
    specificity: "double IPA",
    prices: [4.6, 8.3, 5.8],
    strength: 7.6,
  },
  {
    id: "a15",
    name: "La chouffe",
    prices: [4.2, 7.6, 5.4],
    strength: 8.0,
  },
  {
    id: "a16",
    name: "Houblon Chouffe",
    specificity: "IPA",
    prices: [4.8, 8.6, 6.3],
    strength: 9.0,
  },
  {
    id: "a17",
    name: "Vedett IPA",
    specificity: "IPA",
    prices: [4.4, 7.9, 5.6],
    strength: 5.0,
  },
  {
    id: "a18",
    name: "Maredsous Brune",
    prices: [4.4, 7.9, 5.9],
    strength: 8.0,
  },
];

export const beers = [
  {
    id: "a19",
    name: "Gueuze",
    brewery: "Lindemans",
    from: "Belgique",
    specificity: "Lambic",
    volume: 25,
    dominance: "Acidulée",
    tags: ["Douce", "Sucrée", "Bonbon"],
    strength: 5.0,
    prices: 4.5,
  },
  {
    id: "a20",
    name: "Duchesse",
    from: "Verhaeghe",
    brewery: "Bourgogne",
    specificity: "rouge des flandres",
    volume: 33,
    dominance: "Acidulée",
    tags: ["Boisée", "Cerise", "Amande"],
    strength: 6.2,
    prices: 6.4,
  },
  {
    id: "b10",
    name: "Petrus aged pale",
    brewery: "De Brabandere",
    from: "Belgique",
    specificity: "sour ale",
    volume: 33,
    dominance: "Acidulée",
    tags: ["Citron", "Bois", "Pomme"],
    strength: 7.3,
    prices: 6.4,
  },
  {
    id: "b11",
    name: "Goudenband",
    brewery: "liefmans",
    from: "belgique",
    specificity: "brune des flandres",
    volume: 33,
    dominance: "Acidulée",
    tags: ["Douce", "Vineuse", "fruits des bois"],
    strength: 8.0,
    prices: 7.2,
  },
  {
    id: "b12",
    name: "Hay diamond",
    brewery: "la débauche",
    from: "france",
    specificity: "sour ale",
    volume: 33,
    dominance: "Acidulée",
    tags: ["Boisée", "Cerise", "Amande"],
    strength: 5.0,
    prices: 7.3,
  },
  {
    id: "b13",
    name: "Oude gueuze cuvée rené",
    brewery: "lindemans",
    from: "belgique",
    specificity: "lambic",
    volume: 37.5,
    dominance: "Acidulée",
    tags: ["Sèche", "Pomme acide", "Citron", "Foin"],
    strength: 5.5,
    prices: 7.4,
  },
  {
    id: "b14",
    name: "Szilvas gomboc",
    brewery: "Mad Scientist",
    from: "Hongrie",
    specificity: "imp pastry sour",
    characteristic: "Lactose",
    volume: 33,
    dominance: "Acidulée",
    tags: ["Fruits murs", "Epices", "Cannelle"],
    strength: 10.0,
    prices: 8.0,
  },
  {
    id: "b15",
    name: "Fruitesse",
    brewery: "Liefmans",
    from: "Belgique",
    specificity: "Bière aux fruits",
    characteristic: "Alcohol Free",
    volume: 25,
    dominance: "Sucrée",
    tags: ["Fruits rouges", "Céréales", "Bonbon acidulé"],
    strength: 0.5,
    prices: 4.2,
  },
  {
    id: "b16",
    name: "Apple",
    brewery: "Lindemans",
    from: "Belgique",
    specificity: "Lambic",
    volume: 25,
    dominance: "Sucrée",
    tags: ["Acidulée", "Bonbon", "Pomme"],
    strength: 3.5,
    prices: 4.5,
  },
  {
    id: "b17",
    name: "Framboise",
    brewery: "Lindemans",
    from: "Belgique",
    specificity: "Lambic",
    volume: 25,
    dominance: "Sucrée",
    tags: ["Douce", "Framboise", "Légère"],
    strength: 2.5,
    prices: 5.2,
  },
  {
    id: "b18",
    name: "Pêcheresse",
    brewery: "Lindemans",
    from: "Belgique",
    specificity: "Lambic",
    volume: 25,
    dominance: "Sucrée",
    tags: ["Douce", "Pêche", "Acidulée"],
    strength: 2.5,
    prices: 5.2,
  },
  {
    id: "b19",
    name: "Petrus Aged Red",
    brewery: "De Brabandere",
    from: "Belgique",
    specificity: "Bière aux fruits",
    volume: 33,
    dominance: "Sucrée",
    tags: ["Douce", "Cerise", "Boisée"],
    strength: 8.5,
    prices: 5.6,
  },
  {
    id: "b20",
    name: "Wit",
    brewery: "St.Bernardus",
    from: "Belgique",
    specificity: "Blanche",
    volume: 33,
    dominance: "Douce",
    tags: ["Agrumes", "Céréales", "Coriandre"],
    strength: 5.5,
    prices: 4.0,
  },
  {
    id: "c10",
    name: "Grisette Blonde Bio",
    brewery: "St-Feuillien",
    from: "Belgique",
    specificity: "Sans Gluten",
    characteristic: "Bio, sans gluten",
    volume: 25,
    dominance: "Douce",
    tags: ["Céreales", "Fruits jaunes", "Épicée"],
    strength: 5.5,
    prices: 4.3,
  },
  {
    id: "c11",
    name: "Celebrator",
    brewery: "Ayinger",
    from: "Allemagne",
    specificity: "DoppelBock",
    volume: 33,
    dominance: "Douce",
    tags: ["Maltée", "Épicée", "Biscuit"],
    strength: 6.7,
    prices: 5.2,
  },
  {
    id: "c12",
    name: "Saison Dupont",
    brewery: "Dupont",
    from: "Belgique",
    specificity: "Saison",
    volume: 33,
    dominance: "Douce",
    tags: ["Pétillante", "Désaltérante", "Herbe"],
    strength: 6.5,
    prices: 5.5,
  },
  {
    id: "c13",
    name: "Urweise",
    brewery: "Ayinger",
    from: "Allemagne",
    specificity: "Dunkelweizen",
    volume: 50,
    dominance: "Douce",
    tags: ["Maltée", "Blé", "Épices", "Banane"],
    strength: 5.8,
    prices: 5.8,
  },
  {
    id: "c14",
    name: "Energybajer",
    brewery: "Mikkeller",
    from: "Danemark",
    specificity: "Sans alcool",
    characteristic: "Sans alcool",
    volume: 33,
    dominance: "Douce",
    tags: ["Grain", "Fruits jaune"],
    strength: 0.0,
    prices: 5.9,
  },
  {
    id: "c15",
    name: "Triple d'anvers",
    brewery: "De Koninck",
    from: "Belgique",
    specificity: "Triple",
    volume: 33,
    dominance: "Douce",
    tags: ["Ronde", "Maltée", "slisée    ", "Épices"],
    strength: 8.0,
    prices: 6.4,
  },
  {
    id: "c16",
    name: "Rochefort Triple",
    brewery: "Abbaye St-Remy",
    from: "Belgique",
    specificity: "Triple",
    volume: 33,
    dominance: "Douce",
    tags: ["Moelleuse", "agrumes", "fruitée"],
    strength: 8.1,
    prices: 6.3,
  },
  {
    id: "c17",
    name: "Delirium Tremens",
    brewery: "Huyghe",
    from: "Belgique",
    specificity: "Blonde belge forte",
    volume: 33,
    dominance: "Douce",
    tags: ["Ronde", "Céréales", "Caramélisée", "Épices"],
    strength: 8.5,
    prices: 6.3,
  },
  {
    id: "c18",
    name: "Lupulus Blonde",
    brewery: "Lupulus",
    from: "Belgique",
    specificity: "Belgian Tripel",
    volume: 33,
    dominance: "Douce",
    tags: ["Ronde", "Fruitée", "Épicée", "Grain"],
    strength: 8.5,
    prices: 6.3,
  },
  {
    id: "c19",
    name: "Organicus",
    brewery: "Lupulus",
    from: "Belgique",
    specificity: "Belgian Tripel Bio",
    characteristic: "Bio",
    volume: 33,
    dominance: "Douce",
    tags: ["Fruitée", "Florale", "Végétale"],
    strength: 8.5,
    prices: 6.3,
  },
  {
    id: "c20",
    name: "Aecht",
    alt: "Schlenkerla Rauchbier Märzen",
    brewery: "Heller",
    from: "Allemagne",
    specificity: "Rauchbier",
    volume: 50,
    dominance: "Douce",
    tags: ["Intensément fumée", "Boisée", "Épicée"],
    strength: 5.1,
    prices: 6.5,
  },
  {
    id: "d10",
    name: "Carolus Classic",
    brewery: "Het Anker",
    from: "Belgique",
    specificity: "Brune Belge Forte",
    volume: 33,
    dominance: "Douce",
    tags: ["Maltée", "Caramélisée", "Écorce d'orange"],
    strength: 8.5,
    prices: 6.5,
  },
  {
    id: "d11",
    name: "Rochefort 8",
    brewery: "Abbaye St.Remy",
    from: "Belgique",
    specificity: "Brune Belge Forte",
    volume: 33,
    dominance: "Douce",
    tags: ["Fruitée", "Réglisse", "Caramel"],
    strength: 9.2,
    prices: 6.5,
  },
  {
    id: "d12",
    name: "St Feuillien",
    brewery: "St-Feuillien",
    from: "Belgique",
    specificity: "Blonde Belge Forte",
    volume: 33,
    dominance: "Douce",
    tags: ["Ronde", "Amère", "Pétillante"],
    strength: 9.5,
    prices: 6.5,
  },
  {
    id: "d13",
    name: "Tap 5",
    alt: "Meine Hopfenweisse",
    brewery: "Schneider Weisse",
    from: "Allemagne",
    specificity: "Weizenbock",
    volume: 50,
    dominance: "Douce",
    tags: ["Fruitée", "Épicée", "Céreales"],
    strength: 8.2,
    prices: 6.9,
  },
  {
    id: "d14",
    name: "Carte Blanche",
    brewery: "The Piggy Brewing Company",
    from: "France",
    specificity: "Blanche",
    volume: 33,
    dominance: "Douce",
    tags: ["Florale", "Céreales", "Mandarine"],
    strength: 5.0,
    prices: 7.2,
  },
  {
    id: "d15",
    name: "Must Kuld",
    brewery: "Põhjala",
    from: "Estonie",
    specificity: "Porter",
    characteristic: "Lactose",
    volume: 33,
    dominance: "Douce",
    tags: ["Cacao", "Miel", "Baies"],
    strength: 7.8,
    prices: 7.2,
  },
  {
    id: "d16",
    name: "RocheFort 10",
    brewery: "Abbaye St-Remy",
    from: "Belgique",
    specificity: "Quadruple",
    volume: 33,
    dominance: "Douce",
    tags: ["Fruitée", "Racine", "Chocolat noir"],
    strength: 11.3,
    prices: 7.2,
  },
  {
    id: "d17",
    name: "Öö",
    brewery: "Põhjala",
    from: "Estonie",
    specificity: "Imperial Baltic Porter",
    volume: 33,
    dominance: "Douce",
    tags: ["Moelleuse", "Café", "Caramel salé"],
    strength: 10.5,
    prices: 7.8,
  },
  {
    id: "d18",
    name: "Cognac Barrel",
    brewery: "La débauche",
    from: "France",
    specificity: "Barley Wine",
    volume: 33,
    dominance: "Douce",
    tags: ["Fruits secs", "Bois", "Cognac"],
    strength: 9.5,
    prices: 8.0,
  },
  {
    id: "d19",
    name: "Monstruous",
    alt: "Fat Pig Stout Mexican Cake Edition",
    brewery: "The Piggy Brewing Company",
    from: "France",
    specificity: "Imperial Oatmeal Stout",
    volume: 33,
    dominance: "Douce",
    tags: ["Onctueuse", "Cacao", "Pimentée"],
    strength: 12.0,
    prices: 8.8,
  },
  {
    id: "e10",
    name: "Cocobänger",
    brewery: "Põhjala",
    from: "Estonie",
    specificity: "Imperial Stout",
    volume: 33,
    dominance: "Douce",
    tags: ["Caramel", "Café", "Noix de coco"],
    strength: 12.5,
    prices: 8.8,
  },
  {
    id: "e11",
    name: "Duvel",
    brewery: "Duvel",
    from: "Belgique",
    specificity: "Blonde Belge Forte",
    volume: 33,
    dominance: "Amère",
    tags: ["Sèche", "Zestes d'orange", "Zeste de citron"],
    strength: 8.5,
    prices: 6.2,
  },
  {
    id: "e12",
    name: "Everyday IPA",
    brewery: "Oppigârds",
    from: "Suède",
    specificity: "Session IPA",
    volume: 33,
    dominance: "Amère",
    tags: ["Sèche", "Zestes", "Herbe coupée"],
    strength: 4.6,
    prices: 5.7,
  },
  {
    id: "e13",
    name: "Tundra",
    brewery: "Põhjala",
    from: "Estonie",
    specificity: "IPA sans alcool",
    characteristic: "Sans alcool",
    volume: 33,
    dominance: "Amère",
    tags: ["Résine", "Zestes de citron", "Céréales"],
    strength: 0.5,
    prices: 5.8,
  },
  {
    id: "e14",
    name: "Orval",
    brewery: "Abbaye d'Orval",
    from: "Belgique",
    specificity: "Spéciale Belge",
    volume: 33,
    dominance: "Amère",
    tags: ["Sèche", "Poivrée"],
    strength: 6.2,
    prices: 5.8,
  },
  {
    id: "e15",
    name: "WestMalle Triple",
    brewery: "Abbaye de Westmalle",
    from: "Belgique",
    specificity: "Triple",
    volume: 33,
    dominance: "Amère",
    tags: ["Sèche", "Banane", "Agrumes"],
    strength: 9.5,
    prices: 6.2,
  },
  {
    id: "e16",
    name: "Indian Tribute",
    brewery: "Oppiguârds",
    from: "Suède",
    specificity: "American IPA",
    volume: 33,
    dominance: "Amère",
    tags: ["Orange", "Caramel", "Épices", "Réglisse"],
    strength: 6.6,
    prices: 6.7,
  },
  {
    id: "e17",
    name: "New Sweden IPA",
    brewery: "Oppiguârds",
    from: "Suède",
    specificity: "New England IPA",
    volume: 33,
    dominance: "Amère",
    tags: ["Fruits jaune", "Fruits tropicaux", "Céréales", "Épices"],
    strength: 6.2,
    prices: 6.9,
  },
  {
    id: "e18",
    name: "Duvel",
    alt: "Tripel Hop Citra",
    brewery: "Duvel",
    from: "Belgique",
    specificity: "Blonde Belge Forte",
    volume: 33,
    dominance: "Amère",
    tags: ["Fruitée", "Pamplemousse", "Épicée"],
    strength: 9.5,
    prices: 7.5,
  },
  {
    id: "e19",
    name: "Bons vœux",
    brewery: "Dupont",
    from: "Belgique",
    specificity: "Triple",
    volume: 37.5,
    dominance: "Amère",
    tags: ["Sèche", "Moelleuse", "Houblonnée"],
    strength: 9.5,
    prices: 7.0,
  },
  {
    id: "e20",
    name: "Eroica",
    brewery: "The Piggy Brewing Company",
    from: "France",
    specificity: "New England IPA",
    volume: 33,
    dominance: "Amère",
    tags: ["Sèche", "Pamplemousse", "Fruits exotiques"],
    strength: 6.1,
    prices: 7.5,
  },
  {
    id: "f10",
    name: "La Fougue",
    brewery: "La Diettante",
    from: "France",
    specificity: "IPA BIO",
    characteristic: "Bio",
    volume: 33,
    dominance: "Amère",
    tags: ["Agrumes", "Épices", "Résine"],
    strength: 6.0,
    prices: 7.8,
  },
  {
    id: "f11",
    name: "La Bagarre",
    brewery: "La Diettante",
    from: "France",
    specificity: "Black IPA BIO",
    characteristic: "Bio",
    volume: 33,
    dominance: "Amère",
    tags: ["Torréfiée", "Café", "Agrumes"],
    strength: 6.0,
    prices: 7.8,
  },
  {
    id: "f12",
    name: "Popstar",
    brewery: "Mad Scientist",
    from: "Hongrie",
    specificity: "IPA sans Gluten",
    characteristic: "Sans Gluten",
    volume: 44,
    dominance: "Amère",
    tags: ["Torréfiée", "Café", "Agrumes"],
    strength: 6.5,
    prices: 8.0,
  },
  {
    id: "f13",
    name: "Liquid Cocaine",
    brewery: "Mad Scientist",
    from: "Hongrie",
    specificity: "Impérial IPA",
    volume: 44,
    dominance: "Amère",
    tags: ["Fruitée", "Caramel", "Résine"],
    strength: 9.0,
    prices: 8.4,
  },
];

export const rhum = [
  {
    id: "f14",
    name: "Clairin Communal",
    volume: 4,
    tags: ["Fruité", "Floral", "Végétal", "Foin coupé"],
    strength: 43,
    prices: 6.9,
  },
  {
    id: "f15",
    name: "Plantation Pineapple",
    volume: 4,
    tags: ["Ananas", "Caramel"],
    strength: 40,
    prices: 7.4,
  },
  {
    id: "f16",
    name: "Fair XO",
    volume: 4,
    tags: ["Rond", "Fruit sec", "Vanille", "Épicé"],
    strength: 40,
    prices: 7.4,
  },
  {
    id: "f17",
    name: "Kirk'n Sweeney",
    volume: 4,
    tags: ["Fruit sec", "Caramel", "Vanille"],
    strength: 40,
    prices: 8.4,
  },
  {
    id: "f18",
    name: "Hampden 8 ans",
    volume: 4,
    tags: ["Fruit mûr", "Épicé", "Boisé"],
    strength: 46,
    prices: 9.2,
  },
];

export const whiskies = [
  {
    id: "f19",
    name: "Kavalan DS n°1",
    volume: 4,
    tags: ["Fruité", "Caramel"],
    strength: 40,
    prices: 8.5,
  },
  {
    id: "f20",
    name: "Nikka Coffee Grain",
    volume: 4,
    tags: ["Rond", "Céréales", "Fruité"],
    strength: 45,
    prices: 8.8,
  },
  {
    id: "g10",
    name: "Kilchoman Machir Bay",
    volume: 4,
    tags: ["Fumé", "Iodé"],
    strength: 46,
    prices: 8.8,
  },
  {
    id: "g11",
    name: "Redbreast 12 ans",
    volume: 4,
    tags: ["Fruité", "Floral", "Miel"],
    strength: 40,
    prices: 9.2,
  },
];

export const cocktails = [
  {
    id: "g12",
    name: "Gin Tonic Nikka Coffey Grain",
    volume: 14,
    tags: ["Gin Nikka (4 cl)", "TonicWater FeverTree (20 cl)"],
    prices: 11.0,
  },
  {
    id: "g13",
    name: "After Glow",
    characteristic: "Sans alcool",
    volume: 33,
    tags: ["Nectar d'anans", "Jus d'orange", "Sirop de grenadine"],
    prices: 5.8,
  },
  {
    id: "g14",
    name: "Pineapple Limonade",
    characteristic: "Sans alcool",
    volume: 33,
    tags: ["Nectar d'anans", "Jus d'orange", "Limonade", "Sirop pêche"],
    prices: 5.8,
  },
  {
    id: "g15",
    name: "Mexicana",
    volume: 12,
    tags: ["Tequila ( 4cl )", "Nectar d'ananas", "Jus de citron", "Sirop de grenadine"],
    prices: 8.0,
  },
  {
    id: "g16",
    name: "Daïquiri",
    volume: 7,
    tags: ["Rhum blanc ( 4cl )", "Sucre de canne", "Jus de citron vert"],
    prices: 8.0,
  },
  {
    id: "g17",
    name: "Tequila Sunrise",
    volume: 20,
    tags: ["Tequila ( 6cl )", "Jus d'orange", "Sirop de grenadine"],
    prices: 10.0,
  },
  {
    id: "g18",
    name: "Jamaica Passion",
    volume: 14,
    tags: ["Rhum vieux ( 4cl )", "Cognac ( 2cl )", "Jus de citron", "Nectar d'ananas", "Sirop de passion"],
    prices: 12.0,
  },
  {
    id: "g19",
    name: "Long Island And ice Tea",
    volume: 21,
    tags: [
      "Gin ( 2cl )",
      "Vodka ( 2cl )",
      "Rhum ( 2cl )",
      "Triple sec ( 1cl )",
      "Jus d'orange",
      "Jus de citron vert",
      "Cola",
    ],
    prices: 12.0,
  },
];

export const alcohol = [
  {
    id: "g20",
    name: "Gin Tonic Nikka X Fever Tree",
    volume: 14,
    prices: 11.0,
  },
  {
    id: "h10",
    name: "Amer Bière (Pils et Picon Bière)",
    volume: 25,
    prices: 4.0,
  },
  {
    id: "h11",
    name: "Martini Blanc ou Rouge",
    volume: 6,
    strength: 14.4,
    prices: 4.0,
  },
  {
    id: "h12",
    name: "Vodka Potocki",
    volume: 6,
    strength: 40,
    prices: 9.0,
  },
  {
    id: "h13",
    name: "Gin Nikka Coffey Grain",
    volume: 4,
    strength: 47,
    prices: 9.0,
  },
];

export const freeAlcohol = [
  {
    id: "h14",
    name: "Bière Fruitesse",
    brewery: "Liefmans",
    from: "Belgique",
    specificity: "Bière aux fruits",
    volume: 25,
    tags: ["Sucrée", "Fruits rouges", "Céréales", "Bonbon acidulé"],
    strength: 0.5,
    prices: [4.0, 2.95],
  },
  {
    id: "h15",
    name: "Tundra",
    brewery: "Põhjala",
    from: "Estonie",
    characteristic: "Sans alcool",
    volume: 33,
    tags: ["Amère", "Résine", "Zestes de citron", "Céréales"],
    strength: 0.5,
    prices: [5.8, 4.2],
  },
  {
    id: "h16",
    name: "Energybajer",
    brewery: "Mikkeller",
    from: "Danemark",
    characteristic: "Sans alcool",
    volume: 33,
    tags: ["Douce", "Grain", "Fruits jaune"],
    prices: [5.9, 4.3],
  },
  {
    id: "h17",
    name: "Vittel",
    volume: 25,
    prices: [2.5, 1.8],
  },
  {
    id: "h18",
    name: "Limonade",
    volume: 33,
    prices: [2.5, 1.8],
  },
  {
    id: "h19",
    name: "Sirop À L'eau",
    tags: ["Pêche", "Fraise", "Grenadine", "Menthe", "Citron clair", "Citron acide", "Fruit de la passion"],
    volume: 33,
    prices: [2.5, 1.8],
  },
  {
    id: "h20",
    name: "Schweppes",
    volume: 25,
    prices: [3.5, 2.5],
  },
  {
    id: "i10",
    name: "Perrier",
    volume: 33,
    prices: [3.5, 2.5],
  },
  {
    id: "i20",
    name: "Fritz-Kola, Fritz-Kola (sans sucre), Fritz-Limo orange",
    volume: 33,
    prices: [4.0, 2.9],
  },
  {
    id: "i30",
    name: "Jus de fruits Bio",
    characteristic: "Bio",
    tags: ["Abricot", "Pomme", "Poire", "Pomme-Fraise"],
    volume: 25,
    prices: [4.0, 2.9],
  },
];

export const supplements = [
  { id: "i40", name: "Sirop", volume: 2, prices: 0.3 },
  { id: "i50", name: "Soda ou jus de fruits (abricot, banane, orange, ananas)", volume: 10, prices: 1.0 },
];

export const food = [
  {
    id: "i60",
    name: "Saucisson sec boboss",
    weight: 200,
    prices: 6.5,
  },
  {
    id: "i70",
    name: "Biscuit (pur beurre di buffala)",
    weight: 100,
    prices: 2.0,
  },
  {
    id: "i80",
    name: "St félicien",
    weight: 200,
    prices: 7.5,
  },
  {
    id: "i90",
    name: "Beaumont de savoie",
    weight: 100,
    prices: 3.0,
  },
];
